In [1]:
import pandas as pd

Compare the information gain of partitions by learned strategy to the entropy method

In [2]:
# information gain given by the ILP learned strategy
partition_to_entropy = pd.read_csv('test/partition_to_entropy.csv', index_col=0).fillna(0)

# Entropy calculated from minimal (hypothesis space) reduction ratio
entropy = pd.read_csv('data/entropy.csv', index_col=0)[1:]

display(partition_to_entropy)
display(entropy)

,a,b,c,d,e,f,g,h,i,j
ex_1,0.811278,0.811278,0.811278,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_2,0.721928,0.721928,0.970951,0.970951,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_3,0.650022,0.650022,1.000000,0.918296,0.650022,0.000000,0.000000,0.000000,0.000000,0.000000
ex_4,0.591673,0.591673,0.591673,0.591673,0.985228,0.985228,0.985228,0.000000,0.000000,0.000000
ex_5,0.591673,0.863121,0.985228,0.591673,0.591673,0.863121,0.863121,0.000000,0.000000,0.000000
ex_6,0.543564,0.543564,0.811278,0.543564,0.543564,0.954434,0.811278,1.000000,0.000000,0.000000
ex_7,0.468996,0.468996,0.468996,0.468996,0.721928,0.721928,0.468996,0.468996,0.721928,0.881291
ex_8,0.918296,0.918296,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_9,0.811278,1.000000,0.811278,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_10,0.721928,0.721928,0.721928,0.970951,0.970951,0.000000,0.000000,0.000000,0.000000,0.000000
ex_11,0.650022,0.650022,0.650022,1.000000,0.918296,0.000000,0.000000,0.000000,0.000000,0.000000
ex_12,0.650022,0.650022,0.918296,0.918296,0.650022,0.000000,0.000000,0.000000,0.000000,0.000000
ex_13,0.591673,0.863121,0.591673,0.985228,0.985228,0.591673,0.000000,0.000000,0.000000,0.000000
ex_14,0.543564,0.543564,0.811278,0.954434,0.811278,1.000000,0.954434,0.954434,0.000000,0.000000

,a,b,c,d,e,f,g,h,i,j
ex_1,0.811278,0.811278,0.811278,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_2,0.721928,0.721928,0.970951,0.970951,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_3,0.650022,0.650022,1.000000,0.918296,0.650022,0.000000,0.000000,0.000000,0.000000,0.000000
ex_4,0.591673,0.591673,0.591673,0.591673,0.985228,0.985228,0.985228,0.000000,0.000000,0.000000
ex_5,0.591673,0.863121,0.985228,0.591673,0.591673,0.863121,0.863121,0.000000,0.000000,0.000000
ex_6,0.543564,0.543564,0.811278,0.543564,0.543564,0.954434,0.811278,1.000000,0.000000,0.000000
ex_7,0.468996,0.468996,0.468996,0.468996,0.721928,0.721928,0.468996,0.468996,0.721928,0.881291
ex_8,0.918296,0.918296,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_9,0.811278,1.000000,0.811278,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ex_10,0.721928,0.721928,0.721928,0.970951,0.970951,0.000000,0.000000,0.000000,0.000000,0.000000
ex_11,0.650022,0.650022,0.650022,1.000000,0.918296,0.000000,0.000000,0.000000,0.000000,0.000000
ex_12,0.650022,0.650022,0.918296,0.918296,0.650022,0.000000,0.000000,0.000000,0.000000,0.000000
ex_13,0.591673,0.863121,0.591673,0.985228,0.985228,0.591673,0.000000,0.000000,0.000000,0.000000
ex_14,0.543564,0.543564,0.811278,0.954434,0.811278,1.000000,0.954434,0.954434,0.000000,0.000000

Is every partition giving the same information gain as the entropy method?

In [3]:
def compare_rows(row1, row2):
    return row1 == row2

# Apply the comparison row by row
print(partition_to_entropy.apply(lambda row: compare_rows(row, entropy.loc[row.name]), axis=1))

          a     b     c     d     e     f     g     h     i     j
ex_1   True  True  True  True  True  True  True  True  True  True
ex_2   True  True  True  True  True  True  True  True  True  True
ex_3   True  True  True  True  True  True  True  True  True  True
ex_4   True  True  True  True  True  True  True  True  True  True
ex_5   True  True  True  True  True  True  True  True  True  True
ex_6   True  True  True  True  True  True  True  True  True  True
ex_7   True  True  True  True  True  True  True  True  True  True
ex_8   True  True  True  True  True  True  True  True  True  True
ex_9   True  True  True  True  True  True  True  True  True  True
ex_10  True  True  True  True  True  True  True  True  True  True
ex_11  True  True  True  True  True  True  True  True  True  True
ex_12  True  True  True  True  True  True  True  True  True  True
ex_13  True  True  True  True  True  True  True  True  True  True
ex_14  True  True  True  True  True  True  True  True  True  True